name: Backend linting and unit tests
 
on:
  push:
    branches:
      - main
  pull_request:
 
env:
  NODE_VERSION: 16
 
jobs:
  linting-and-tests:
    name: Backend linting and unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
 
      - name: Code Checkout
        uses: actions/checkout@v2
 
      - name: Install backend dependencies
        run: yarn --cwd ./packages/backend install --frozen-lockfile

      - name: Build backend
        run: yarn --cwd ./packages/backend build
 
      - name: Backend code linting
        run: yarn --cwd ./packages/backend lint --quiet

      - name: Backend unit test
        run: yarn --cwd ./packages/backend test
